### ISSUE TITLE
Criação de página web

### ISSUE THREAD

**Issue by mvfsillva** [YanMagale/gulp-utilization#2]
Que tal criarmos uma página web com esse repositório, creio que seria bastante interessante.
O que acha?

**Comment by yanmagale** [comment]
Excelente ideia @mvfsilva. Eu quero adicionar mais exemplos de outros plugins, pra quando criarmos a página web já termos uma quantidade considerável de exemplos. Ou podemos ir fazendo as duas coisas de forma simultânea. O que acha ?

**Comment by mvfsillva** [comment]
Beleza, vou colocar alguns exemplos também!
